language: node_js
node_js:
  - "node"
services:
  - docker
install:
  - npm i
script: npm run test:ci
after_success:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - npm run build
  - npm run deploy
